mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:/mappers/**.xml
  type-aliases-package: com.lianxiao.demo.simpleserver.model

mapper:
  mappers: com.lianxiao.demo.simpleserver.util.MyMapper
  not-empty: true
  identity: MYSQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolink.test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5